name: Github Actions Demo
on: [push]
jobs:
  Explore-Github-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "The job is running on a ${{ runner.os }} server"
      - run: echo "The name of your branch is ${{ github.ref }} and your repo ${{ github.repository }}."
      - name: Checkout repository code
        uses: actions/checkout@v2
      - run: echo "The repository ${{ github.repository }} has been cloned to the runner."
      - run: echo "The workflow is now ready to test your code on the runner."
      - run: |
          ls ${{ github.workspace }}
      - run: echo "The job status is ${{ job.status }}."
